### ISSUE TITLE
Move class Coord in a structure

### ISSUE THREAD

**Issue by skeggib** [skeggib/Glaw#2]

**Comment by palra** [comment]
https://github.com/palra/FxGL/blob/master/Vectors.h
Just have to change the name of the struct

**Comment by skeggib** [comment]
Thanks :D I think I will keep the name, "Vector" is more appropriate than "Coord"

**Comment by palra** [comment]
So do we keep speaking english ?

**Comment by skeggib** [comment]
En anglais c'est bien, ça me permet de m'entraîner ^^
